// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GrowHub",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "GrowHub",
            targets: ["AppModule"],
            bundleIdentifier: "com.timoeichelmann.GrowHub",
            teamIdentifier: "B7N536M863",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .carrot),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "Allow GrowHub to access your photo library to save images of your plants in the app."),
                .calendars(purposeString: "Let GrowHub access your calendar and add events like watering or harvesting to your calendar.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
